### PR TITLE
cssBSalthoIloveCSS

### PR DESCRIPTION
**Pull request by katherinejhwang**
Hi,  this is what we did:

1. We will be using inline CSS styling so we deleted all unnecessary .css files;
2. We created a lesson.html by accident, which we will delete;
3. We created a wrapper.js;
4.  We deleted defaulted lines of code in index.js (i.e. serviceWorker)

### CODE REVIEW

**Comment by katherinejhwang** [comment]
@zanethomas, perfect timing on your comments.  @gglinoga and I were just discussing that and decided that was the better "route" to go by.  hahaha.  @erikchan103 is handling the routes for us and we will be adding React's Router tomorrow.  Thanks!

**Comment by zanethomas** [comment]
ok, so what do you want to do with this PR, close without merge?

**Comment by katherinejhwang** [comment]
@zanethomas, go ahead and merge it.  I just did a PR entitled "pages" which adds a "pages" directory, which will hold our .js files for the pages we will be routing through our App.js file.

**Comment by zanethomas** [comment]
So here's the thing. If you have a PR which is being replaced by a different approach then what's the point in merging the PR. Is there something of value in that PR? If not then maybe the entire branch should just be forgotten. Otherwise the parts of it which have no value should be discarded in the branch. The corresponding PR will update (after branch commit and push) and then the PR as modified can be committed.

**Comment by katherinejhwang** [comment]
@zanethomas, can you approve PR #5 and we will delete PR #3?

**Pull request closed without merging**
